### ISSUE TITLE
判断指定字段为null或空字符串的逻辑无法达成

### ISSUE THREAD

**Issue by Champion-Chen** [dotnetcore/osharp#98] opened 2019-06-06 03:06 UTC
例如：返回所有ParentId为null的记录，如Field: ParentId, value: null, Operator: Equal，结果被翻译成 m => true, 查源码，如下：
  private Expression GetExpressionBody(ParameterExpression param, FilterRule rule)
    {
      if (rule == null || rule.Value == null || string.IsNullOrEmpty(rule.Value.ToString()))
        return (Expression) Expression.Constant((object) true);
      LambdaExpression lambdaExpression = FilterService.GetPropertyLambdaExpression(param, rule);
      Expression expression = this.ChangeTypeToExpression(rule, lambdaExpression.Body.Type);
      return FilterService.ExpressionDict[rule.Operate](lambdaExpression.Body, expression);
    }

似乎可以考虑引入 IsNull 和 IsEmptyString的操作，或把上面 rule.value==null和后面的逻辑兼容掉

**Comment by gmf520** [comment] 2019-06-06 08:57
Duplicate of #94

**Closed as completed** 2019-06-12 04:45 UTC
Labels: Duplicate :performing_arts:
